language: python
python:
  - "3.6"
  - "3.7"
install: 
  - pip install setuptools>=39 --upgrade
  - pip install -U tox coveralls pyserial pyserial-asyncio
  - pip install -r requirements.txt
script: travis_wait 30 pytest tests
after_sucess: coveralls
