language: python
python: 
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install coverage"
script:
  - "coverage run --source=heatmiserV3 setup.py test"
after_success:
  converalls
